language: node_js
cache: yarn
node_js:
  - 12

before_script:
  - npm install -g codecov
  - psql -c 'create database test;' -U postgres

script:
  - yarn run lint
  - yarn run tsc
  - yarn run coverage

services:
  - postgresql

after_success:
  - codecov
